
export const LOAD_TTITLE_LESSONS = 'LOAD_TTITLE_LESSONS'
export const LOAD_TASK_FOR_LESSON = 'LOAD_TASK_FOR_LESSON'
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const INIT_COUNTER = 'INIT_COUNTER'